# Generated by Django 2.1 on 2018-01-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('Active_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Active_Name', models.CharField(max_length=100)),
                ('Active_StartDate', models.DateField()),
                ('Active_EndDate', models.DateField()),
                ('Active_UserName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveType',
            fields=[
                ('ActiveType_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ActiveType_Name', models.CharField(max_length=50)),
            ],
        ),
    ]
